//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApplication.UranusCoreAPIServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthRequestInfo", Namespace="http://www.bayometric.com")]
    [System.SerializableAttribute()]
    public partial class AuthRequestInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ShowGUIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TimeoutField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonID {
            get {
                return this.PersonIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonIDField, value) != true)) {
                    this.PersonIDField = value;
                    this.RaisePropertyChanged("PersonID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ShowGUI {
            get {
                return this.ShowGUIField;
            }
            set {
                if ((this.ShowGUIField.Equals(value) != true)) {
                    this.ShowGUIField = value;
                    this.RaisePropertyChanged("ShowGUI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Timeout {
            get {
                return this.TimeoutField;
            }
            set {
                if ((this.TimeoutField.Equals(value) != true)) {
                    this.TimeoutField = value;
                    this.RaisePropertyChanged("Timeout");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BFSResponseBase", Namespace="http://www.bayometric.com")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SampleApplication.UranusCoreAPIServiceReference.BFSResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SampleApplication.UranusCoreAPIServiceReference.BFSInfoResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SampleApplication.UranusCoreAPIServiceReference.BFSAuthResponse))]
    public partial class BFSResponseBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SampleApplication.UranusCoreAPIServiceReference.BFSClientReturnErrorCode ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SampleApplication.UranusCoreAPIServiceReference.BFSClientReturnErrorCode ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((this.ResponseCodeField.Equals(value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnMessage {
            get {
                return this.ReturnMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnMessageField, value) != true)) {
                    this.ReturnMessageField = value;
                    this.RaisePropertyChanged("ReturnMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BFSResponse", Namespace="http://www.bayometric.com")]
    [System.SerializableAttribute()]
    public partial class BFSResponse : SampleApplication.UranusCoreAPIServiceReference.BFSResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonFoundIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonFoundID {
            get {
                return this.PersonFoundIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonFoundIDField, value) != true)) {
                    this.PersonFoundIDField = value;
                    this.RaisePropertyChanged("PersonFoundID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonID {
            get {
                return this.PersonIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonIDField, value) != true)) {
                    this.PersonIDField = value;
                    this.RaisePropertyChanged("PersonID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BFSInfoResponse", Namespace="http://www.bayometric.com")]
    [System.SerializableAttribute()]
    public partial class BFSInfoResponse : SampleApplication.UranusCoreAPIServiceReference.BFSResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] RegisteredPersonsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] RegisteredPersons {
            get {
                return this.RegisteredPersonsField;
            }
            set {
                if ((object.ReferenceEquals(this.RegisteredPersonsField, value) != true)) {
                    this.RegisteredPersonsField = value;
                    this.RaisePropertyChanged("RegisteredPersons");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BFSAuthResponse", Namespace="http://www.bayometric.com")]
    [System.SerializableAttribute()]
    public partial class BFSAuthResponse : SampleApplication.UranusCoreAPIServiceReference.BFSResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonID {
            get {
                return this.PersonIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonIDField, value) != true)) {
                    this.PersonIDField = value;
                    this.RaisePropertyChanged("PersonID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionKey {
            get {
                return this.SessionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionKeyField, value) != true)) {
                    this.SessionKeyField = value;
                    this.RaisePropertyChanged("SessionKey");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BFSClientReturnErrorCode", Namespace="http://www.bayometric.com")]
    public enum BFSClientReturnErrorCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SUCCESS = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CANCELED_BY_USER = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HIT_CONFIRMED = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NO_HIT = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ALREADY_ENROLLED = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CAPTURE_TIMEOUT = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BAD_IMAGE_QUALITY = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SERVICE_BUSY = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INCORRECT_CALL = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        END_OF_LIST = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NO_READER_CONNECTED = -1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SERVER_CONNECTION_FAILED = -2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SERVER_TIMEOUT = -3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SERVER_ERROR = -4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PERSON_ID_NOT_FOUND = -5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID_LICENSE = -6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LICENSE_MAX_RECORDS = -7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LICENSE_MAX_CLIENTS = -8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LICENSE_EXPIRED = -9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID_SESSION = -10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SESSION_EXPIRED = -11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NOT_ALLOWED_OPERATION = -12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID_CREDENTIALS = -13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID_PARAMETERS = -14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REQUIRES_AUTHENTICATION = -15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        USER_NOT_ACTIVE = -16,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.bayometric.com", ConfigurationName="UranusCoreAPIServiceReference.UranusCore")]
    public interface UranusCore {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bayometric.com/UranusCore/CreateSession", ReplyAction="http://www.bayometric.com/UranusCore/CreateSessionResponse")]
        SampleApplication.UranusCoreAPIServiceReference.BFSAuthResponse CreateSession(SampleApplication.UranusCoreAPIServiceReference.AuthRequestInfo authRequestInfo);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.bayometric.com/UranusCore/CreateSession", ReplyAction="http://www.bayometric.com/UranusCore/CreateSessionResponse")]
        System.IAsyncResult BeginCreateSession(SampleApplication.UranusCoreAPIServiceReference.AuthRequestInfo authRequestInfo, System.AsyncCallback callback, object asyncState);
        
        SampleApplication.UranusCoreAPIServiceReference.BFSAuthResponse EndCreateSession(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bayometric.com/UranusCore/EndSession", ReplyAction="http://www.bayometric.com/UranusCore/EndSessionResponse")]
        SampleApplication.UranusCoreAPIServiceReference.BFSResponseBase EndSession(string sessionKey);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.bayometric.com/UranusCore/EndSession", ReplyAction="http://www.bayometric.com/UranusCore/EndSessionResponse")]
        System.IAsyncResult BeginEndSession(string sessionKey, System.AsyncCallback callback, object asyncState);
        
        SampleApplication.UranusCoreAPIServiceReference.BFSResponseBase EndEndSession(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bayometric.com/UranusCore/RegisterPerson", ReplyAction="http://www.bayometric.com/UranusCore/RegisterPersonResponse")]
        SampleApplication.UranusCoreAPIServiceReference.BFSResponse RegisterPerson(string sessionKey, string personID);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.bayometric.com/UranusCore/RegisterPerson", ReplyAction="http://www.bayometric.com/UranusCore/RegisterPersonResponse")]
        System.IAsyncResult BeginRegisterPerson(string sessionKey, string personID, System.AsyncCallback callback, object asyncState);
        
        SampleApplication.UranusCoreAPIServiceReference.BFSResponse EndRegisterPerson(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bayometric.com/UranusCore/UnregisterPerson", ReplyAction="http://www.bayometric.com/UranusCore/UnregisterPersonResponse")]
        SampleApplication.UranusCoreAPIServiceReference.BFSResponse UnregisterPerson(string sessionKey, string personID);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.bayometric.com/UranusCore/UnregisterPerson", ReplyAction="http://www.bayometric.com/UranusCore/UnregisterPersonResponse")]
        System.IAsyncResult BeginUnregisterPerson(string sessionKey, string personID, System.AsyncCallback callback, object asyncState);
        
        SampleApplication.UranusCoreAPIServiceReference.BFSResponse EndUnregisterPerson(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bayometric.com/UranusCore/Search", ReplyAction="http://www.bayometric.com/UranusCore/SearchResponse")]
        SampleApplication.UranusCoreAPIServiceReference.BFSResponse Search();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.bayometric.com/UranusCore/Search", ReplyAction="http://www.bayometric.com/UranusCore/SearchResponse")]
        System.IAsyncResult BeginSearch(System.AsyncCallback callback, object asyncState);
        
        SampleApplication.UranusCoreAPIServiceReference.BFSResponse EndSearch(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bayometric.com/UranusCore/SearchEx", ReplyAction="http://www.bayometric.com/UranusCore/SearchExResponse")]
        SampleApplication.UranusCoreAPIServiceReference.BFSResponse SearchEx(string appToken, string personID, bool showGUI, int timeout);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.bayometric.com/UranusCore/SearchEx", ReplyAction="http://www.bayometric.com/UranusCore/SearchExResponse")]
        System.IAsyncResult BeginSearchEx(string appToken, string personID, bool showGUI, int timeout, System.AsyncCallback callback, object asyncState);
        
        SampleApplication.UranusCoreAPIServiceReference.BFSResponse EndSearchEx(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bayometric.com/UranusCore/CancelSearch", ReplyAction="http://www.bayometric.com/UranusCore/CancelSearchResponse")]
        SampleApplication.UranusCoreAPIServiceReference.BFSResponse CancelSearch(string appToken);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.bayometric.com/UranusCore/CancelSearch", ReplyAction="http://www.bayometric.com/UranusCore/CancelSearchResponse")]
        System.IAsyncResult BeginCancelSearch(string appToken, System.AsyncCallback callback, object asyncState);
        
        SampleApplication.UranusCoreAPIServiceReference.BFSResponse EndCancelSearch(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bayometric.com/UranusCore/GetRegisteredPersons", ReplyAction="http://www.bayometric.com/UranusCore/GetRegisteredPersonsResponse")]
        SampleApplication.UranusCoreAPIServiceReference.BFSInfoResponse GetRegisteredPersons(int startIndex, int numberOfPersons);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.bayometric.com/UranusCore/GetRegisteredPersons", ReplyAction="http://www.bayometric.com/UranusCore/GetRegisteredPersonsResponse")]
        System.IAsyncResult BeginGetRegisteredPersons(int startIndex, int numberOfPersons, System.AsyncCallback callback, object asyncState);
        
        SampleApplication.UranusCoreAPIServiceReference.BFSInfoResponse EndGetRegisteredPersons(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UranusCoreChannel : SampleApplication.UranusCoreAPIServiceReference.UranusCore, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateSessionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CreateSessionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SampleApplication.UranusCoreAPIServiceReference.BFSAuthResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SampleApplication.UranusCoreAPIServiceReference.BFSAuthResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EndSessionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public EndSessionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SampleApplication.UranusCoreAPIServiceReference.BFSResponseBase Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SampleApplication.UranusCoreAPIServiceReference.BFSResponseBase)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegisterPersonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RegisterPersonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SampleApplication.UranusCoreAPIServiceReference.BFSResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SampleApplication.UranusCoreAPIServiceReference.BFSResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UnregisterPersonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UnregisterPersonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SampleApplication.UranusCoreAPIServiceReference.BFSResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SampleApplication.UranusCoreAPIServiceReference.BFSResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SampleApplication.UranusCoreAPIServiceReference.BFSResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SampleApplication.UranusCoreAPIServiceReference.BFSResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchExCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SearchExCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SampleApplication.UranusCoreAPIServiceReference.BFSResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SampleApplication.UranusCoreAPIServiceReference.BFSResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CancelSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CancelSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SampleApplication.UranusCoreAPIServiceReference.BFSResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SampleApplication.UranusCoreAPIServiceReference.BFSResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetRegisteredPersonsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetRegisteredPersonsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SampleApplication.UranusCoreAPIServiceReference.BFSInfoResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SampleApplication.UranusCoreAPIServiceReference.BFSInfoResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UranusCoreClient : System.ServiceModel.ClientBase<SampleApplication.UranusCoreAPIServiceReference.UranusCore>, SampleApplication.UranusCoreAPIServiceReference.UranusCore {
        
        private BeginOperationDelegate onBeginCreateSessionDelegate;
        
        private EndOperationDelegate onEndCreateSessionDelegate;
        
        private System.Threading.SendOrPostCallback onCreateSessionCompletedDelegate;
        
        private BeginOperationDelegate onBeginEndSessionDelegate;
        
        private EndOperationDelegate onEndEndSessionDelegate;
        
        private System.Threading.SendOrPostCallback onEndSessionCompletedDelegate;
        
        private BeginOperationDelegate onBeginRegisterPersonDelegate;
        
        private EndOperationDelegate onEndRegisterPersonDelegate;
        
        private System.Threading.SendOrPostCallback onRegisterPersonCompletedDelegate;
        
        private BeginOperationDelegate onBeginUnregisterPersonDelegate;
        
        private EndOperationDelegate onEndUnregisterPersonDelegate;
        
        private System.Threading.SendOrPostCallback onUnregisterPersonCompletedDelegate;
        
        private BeginOperationDelegate onBeginSearchDelegate;
        
        private EndOperationDelegate onEndSearchDelegate;
        
        private System.Threading.SendOrPostCallback onSearchCompletedDelegate;
        
        private BeginOperationDelegate onBeginSearchExDelegate;
        
        private EndOperationDelegate onEndSearchExDelegate;
        
        private System.Threading.SendOrPostCallback onSearchExCompletedDelegate;
        
        private BeginOperationDelegate onBeginCancelSearchDelegate;
        
        private EndOperationDelegate onEndCancelSearchDelegate;
        
        private System.Threading.SendOrPostCallback onCancelSearchCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetRegisteredPersonsDelegate;
        
        private EndOperationDelegate onEndGetRegisteredPersonsDelegate;
        
        private System.Threading.SendOrPostCallback onGetRegisteredPersonsCompletedDelegate;
        
        public UranusCoreClient() {
        }
        
        public UranusCoreClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UranusCoreClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UranusCoreClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UranusCoreClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<CreateSessionCompletedEventArgs> CreateSessionCompleted;
        
        public event System.EventHandler<EndSessionCompletedEventArgs> EndSessionCompleted;
        
        public event System.EventHandler<RegisterPersonCompletedEventArgs> RegisterPersonCompleted;
        
        public event System.EventHandler<UnregisterPersonCompletedEventArgs> UnregisterPersonCompleted;
        
        public event System.EventHandler<SearchCompletedEventArgs> SearchCompleted;
        
        public event System.EventHandler<SearchExCompletedEventArgs> SearchExCompleted;
        
        public event System.EventHandler<CancelSearchCompletedEventArgs> CancelSearchCompleted;
        
        public event System.EventHandler<GetRegisteredPersonsCompletedEventArgs> GetRegisteredPersonsCompleted;
        
        public SampleApplication.UranusCoreAPIServiceReference.BFSAuthResponse CreateSession(SampleApplication.UranusCoreAPIServiceReference.AuthRequestInfo authRequestInfo) {
            return base.Channel.CreateSession(authRequestInfo);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginCreateSession(SampleApplication.UranusCoreAPIServiceReference.AuthRequestInfo authRequestInfo, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCreateSession(authRequestInfo, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public SampleApplication.UranusCoreAPIServiceReference.BFSAuthResponse EndCreateSession(System.IAsyncResult result) {
            return base.Channel.EndCreateSession(result);
        }
        
        private System.IAsyncResult OnBeginCreateSession(object[] inValues, System.AsyncCallback callback, object asyncState) {
            SampleApplication.UranusCoreAPIServiceReference.AuthRequestInfo authRequestInfo = ((SampleApplication.UranusCoreAPIServiceReference.AuthRequestInfo)(inValues[0]));
            return this.BeginCreateSession(authRequestInfo, callback, asyncState);
        }
        
        private object[] OnEndCreateSession(System.IAsyncResult result) {
            SampleApplication.UranusCoreAPIServiceReference.BFSAuthResponse retVal = this.EndCreateSession(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCreateSessionCompleted(object state) {
            if ((this.CreateSessionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CreateSessionCompleted(this, new CreateSessionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CreateSessionAsync(SampleApplication.UranusCoreAPIServiceReference.AuthRequestInfo authRequestInfo) {
            this.CreateSessionAsync(authRequestInfo, null);
        }
        
        public void CreateSessionAsync(SampleApplication.UranusCoreAPIServiceReference.AuthRequestInfo authRequestInfo, object userState) {
            if ((this.onBeginCreateSessionDelegate == null)) {
                this.onBeginCreateSessionDelegate = new BeginOperationDelegate(this.OnBeginCreateSession);
            }
            if ((this.onEndCreateSessionDelegate == null)) {
                this.onEndCreateSessionDelegate = new EndOperationDelegate(this.OnEndCreateSession);
            }
            if ((this.onCreateSessionCompletedDelegate == null)) {
                this.onCreateSessionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCreateSessionCompleted);
            }
            base.InvokeAsync(this.onBeginCreateSessionDelegate, new object[] {
                        authRequestInfo}, this.onEndCreateSessionDelegate, this.onCreateSessionCompletedDelegate, userState);
        }
        
        public SampleApplication.UranusCoreAPIServiceReference.BFSResponseBase EndSession(string sessionKey) {
            return base.Channel.EndSession(sessionKey);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginEndSession(string sessionKey, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginEndSession(sessionKey, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public SampleApplication.UranusCoreAPIServiceReference.BFSResponseBase EndEndSession(System.IAsyncResult result) {
            return base.Channel.EndEndSession(result);
        }
        
        private System.IAsyncResult OnBeginEndSession(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string sessionKey = ((string)(inValues[0]));
            return this.BeginEndSession(sessionKey, callback, asyncState);
        }
        
        private object[] OnEndEndSession(System.IAsyncResult result) {
            SampleApplication.UranusCoreAPIServiceReference.BFSResponseBase retVal = this.EndEndSession(result);
            return new object[] {
                    retVal};
        }
        
        private void OnEndSessionCompleted(object state) {
            if ((this.EndSessionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.EndSessionCompleted(this, new EndSessionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void EndSessionAsync(string sessionKey) {
            this.EndSessionAsync(sessionKey, null);
        }
        
        public void EndSessionAsync(string sessionKey, object userState) {
            if ((this.onBeginEndSessionDelegate == null)) {
                this.onBeginEndSessionDelegate = new BeginOperationDelegate(this.OnBeginEndSession);
            }
            if ((this.onEndEndSessionDelegate == null)) {
                this.onEndEndSessionDelegate = new EndOperationDelegate(this.OnEndEndSession);
            }
            if ((this.onEndSessionCompletedDelegate == null)) {
                this.onEndSessionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnEndSessionCompleted);
            }
            base.InvokeAsync(this.onBeginEndSessionDelegate, new object[] {
                        sessionKey}, this.onEndEndSessionDelegate, this.onEndSessionCompletedDelegate, userState);
        }
        
        public SampleApplication.UranusCoreAPIServiceReference.BFSResponse RegisterPerson(string sessionKey, string personID) {
            return base.Channel.RegisterPerson(sessionKey, personID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginRegisterPerson(string sessionKey, string personID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRegisterPerson(sessionKey, personID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public SampleApplication.UranusCoreAPIServiceReference.BFSResponse EndRegisterPerson(System.IAsyncResult result) {
            return base.Channel.EndRegisterPerson(result);
        }
        
        private System.IAsyncResult OnBeginRegisterPerson(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string sessionKey = ((string)(inValues[0]));
            string personID = ((string)(inValues[1]));
            return this.BeginRegisterPerson(sessionKey, personID, callback, asyncState);
        }
        
        private object[] OnEndRegisterPerson(System.IAsyncResult result) {
            SampleApplication.UranusCoreAPIServiceReference.BFSResponse retVal = this.EndRegisterPerson(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRegisterPersonCompleted(object state) {
            if ((this.RegisterPersonCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RegisterPersonCompleted(this, new RegisterPersonCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RegisterPersonAsync(string sessionKey, string personID) {
            this.RegisterPersonAsync(sessionKey, personID, null);
        }
        
        public void RegisterPersonAsync(string sessionKey, string personID, object userState) {
            if ((this.onBeginRegisterPersonDelegate == null)) {
                this.onBeginRegisterPersonDelegate = new BeginOperationDelegate(this.OnBeginRegisterPerson);
            }
            if ((this.onEndRegisterPersonDelegate == null)) {
                this.onEndRegisterPersonDelegate = new EndOperationDelegate(this.OnEndRegisterPerson);
            }
            if ((this.onRegisterPersonCompletedDelegate == null)) {
                this.onRegisterPersonCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRegisterPersonCompleted);
            }
            base.InvokeAsync(this.onBeginRegisterPersonDelegate, new object[] {
                        sessionKey,
                        personID}, this.onEndRegisterPersonDelegate, this.onRegisterPersonCompletedDelegate, userState);
        }
        
        public SampleApplication.UranusCoreAPIServiceReference.BFSResponse UnregisterPerson(string sessionKey, string personID) {
            return base.Channel.UnregisterPerson(sessionKey, personID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginUnregisterPerson(string sessionKey, string personID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUnregisterPerson(sessionKey, personID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public SampleApplication.UranusCoreAPIServiceReference.BFSResponse EndUnregisterPerson(System.IAsyncResult result) {
            return base.Channel.EndUnregisterPerson(result);
        }
        
        private System.IAsyncResult OnBeginUnregisterPerson(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string sessionKey = ((string)(inValues[0]));
            string personID = ((string)(inValues[1]));
            return this.BeginUnregisterPerson(sessionKey, personID, callback, asyncState);
        }
        
        private object[] OnEndUnregisterPerson(System.IAsyncResult result) {
            SampleApplication.UranusCoreAPIServiceReference.BFSResponse retVal = this.EndUnregisterPerson(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUnregisterPersonCompleted(object state) {
            if ((this.UnregisterPersonCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UnregisterPersonCompleted(this, new UnregisterPersonCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UnregisterPersonAsync(string sessionKey, string personID) {
            this.UnregisterPersonAsync(sessionKey, personID, null);
        }
        
        public void UnregisterPersonAsync(string sessionKey, string personID, object userState) {
            if ((this.onBeginUnregisterPersonDelegate == null)) {
                this.onBeginUnregisterPersonDelegate = new BeginOperationDelegate(this.OnBeginUnregisterPerson);
            }
            if ((this.onEndUnregisterPersonDelegate == null)) {
                this.onEndUnregisterPersonDelegate = new EndOperationDelegate(this.OnEndUnregisterPerson);
            }
            if ((this.onUnregisterPersonCompletedDelegate == null)) {
                this.onUnregisterPersonCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUnregisterPersonCompleted);
            }
            base.InvokeAsync(this.onBeginUnregisterPersonDelegate, new object[] {
                        sessionKey,
                        personID}, this.onEndUnregisterPersonDelegate, this.onUnregisterPersonCompletedDelegate, userState);
        }
        
        public SampleApplication.UranusCoreAPIServiceReference.BFSResponse Search() {
            return base.Channel.Search();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSearch(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSearch(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public SampleApplication.UranusCoreAPIServiceReference.BFSResponse EndSearch(System.IAsyncResult result) {
            return base.Channel.EndSearch(result);
        }
        
        private System.IAsyncResult OnBeginSearch(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginSearch(callback, asyncState);
        }
        
        private object[] OnEndSearch(System.IAsyncResult result) {
            SampleApplication.UranusCoreAPIServiceReference.BFSResponse retVal = this.EndSearch(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSearchCompleted(object state) {
            if ((this.SearchCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SearchCompleted(this, new SearchCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SearchAsync() {
            this.SearchAsync(null);
        }
        
        public void SearchAsync(object userState) {
            if ((this.onBeginSearchDelegate == null)) {
                this.onBeginSearchDelegate = new BeginOperationDelegate(this.OnBeginSearch);
            }
            if ((this.onEndSearchDelegate == null)) {
                this.onEndSearchDelegate = new EndOperationDelegate(this.OnEndSearch);
            }
            if ((this.onSearchCompletedDelegate == null)) {
                this.onSearchCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSearchCompleted);
            }
            base.InvokeAsync(this.onBeginSearchDelegate, null, this.onEndSearchDelegate, this.onSearchCompletedDelegate, userState);
        }
        
        public SampleApplication.UranusCoreAPIServiceReference.BFSResponse SearchEx(string appToken, string personID, bool showGUI, int timeout) {
            return base.Channel.SearchEx(appToken, personID, showGUI, timeout);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSearchEx(string appToken, string personID, bool showGUI, int timeout, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSearchEx(appToken, personID, showGUI, timeout, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public SampleApplication.UranusCoreAPIServiceReference.BFSResponse EndSearchEx(System.IAsyncResult result) {
            return base.Channel.EndSearchEx(result);
        }
        
        private System.IAsyncResult OnBeginSearchEx(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string appToken = ((string)(inValues[0]));
            string personID = ((string)(inValues[1]));
            bool showGUI = ((bool)(inValues[2]));
            int timeout = ((int)(inValues[3]));
            return this.BeginSearchEx(appToken, personID, showGUI, timeout, callback, asyncState);
        }
        
        private object[] OnEndSearchEx(System.IAsyncResult result) {
            SampleApplication.UranusCoreAPIServiceReference.BFSResponse retVal = this.EndSearchEx(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSearchExCompleted(object state) {
            if ((this.SearchExCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SearchExCompleted(this, new SearchExCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SearchExAsync(string appToken, string personID, bool showGUI, int timeout) {
            this.SearchExAsync(appToken, personID, showGUI, timeout, null);
        }
        
        public void SearchExAsync(string appToken, string personID, bool showGUI, int timeout, object userState) {
            if ((this.onBeginSearchExDelegate == null)) {
                this.onBeginSearchExDelegate = new BeginOperationDelegate(this.OnBeginSearchEx);
            }
            if ((this.onEndSearchExDelegate == null)) {
                this.onEndSearchExDelegate = new EndOperationDelegate(this.OnEndSearchEx);
            }
            if ((this.onSearchExCompletedDelegate == null)) {
                this.onSearchExCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSearchExCompleted);
            }
            base.InvokeAsync(this.onBeginSearchExDelegate, new object[] {
                        appToken,
                        personID,
                        showGUI,
                        timeout}, this.onEndSearchExDelegate, this.onSearchExCompletedDelegate, userState);
        }
        
        public SampleApplication.UranusCoreAPIServiceReference.BFSResponse CancelSearch(string appToken) {
            return base.Channel.CancelSearch(appToken);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginCancelSearch(string appToken, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCancelSearch(appToken, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public SampleApplication.UranusCoreAPIServiceReference.BFSResponse EndCancelSearch(System.IAsyncResult result) {
            return base.Channel.EndCancelSearch(result);
        }
        
        private System.IAsyncResult OnBeginCancelSearch(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string appToken = ((string)(inValues[0]));
            return this.BeginCancelSearch(appToken, callback, asyncState);
        }
        
        private object[] OnEndCancelSearch(System.IAsyncResult result) {
            SampleApplication.UranusCoreAPIServiceReference.BFSResponse retVal = this.EndCancelSearch(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCancelSearchCompleted(object state) {
            if ((this.CancelSearchCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CancelSearchCompleted(this, new CancelSearchCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CancelSearchAsync(string appToken) {
            this.CancelSearchAsync(appToken, null);
        }
        
        public void CancelSearchAsync(string appToken, object userState) {
            if ((this.onBeginCancelSearchDelegate == null)) {
                this.onBeginCancelSearchDelegate = new BeginOperationDelegate(this.OnBeginCancelSearch);
            }
            if ((this.onEndCancelSearchDelegate == null)) {
                this.onEndCancelSearchDelegate = new EndOperationDelegate(this.OnEndCancelSearch);
            }
            if ((this.onCancelSearchCompletedDelegate == null)) {
                this.onCancelSearchCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCancelSearchCompleted);
            }
            base.InvokeAsync(this.onBeginCancelSearchDelegate, new object[] {
                        appToken}, this.onEndCancelSearchDelegate, this.onCancelSearchCompletedDelegate, userState);
        }
        
        public SampleApplication.UranusCoreAPIServiceReference.BFSInfoResponse GetRegisteredPersons(int startIndex, int numberOfPersons) {
            return base.Channel.GetRegisteredPersons(startIndex, numberOfPersons);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetRegisteredPersons(int startIndex, int numberOfPersons, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetRegisteredPersons(startIndex, numberOfPersons, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public SampleApplication.UranusCoreAPIServiceReference.BFSInfoResponse EndGetRegisteredPersons(System.IAsyncResult result) {
            return base.Channel.EndGetRegisteredPersons(result);
        }
        
        private System.IAsyncResult OnBeginGetRegisteredPersons(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int startIndex = ((int)(inValues[0]));
            int numberOfPersons = ((int)(inValues[1]));
            return this.BeginGetRegisteredPersons(startIndex, numberOfPersons, callback, asyncState);
        }
        
        private object[] OnEndGetRegisteredPersons(System.IAsyncResult result) {
            SampleApplication.UranusCoreAPIServiceReference.BFSInfoResponse retVal = this.EndGetRegisteredPersons(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetRegisteredPersonsCompleted(object state) {
            if ((this.GetRegisteredPersonsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetRegisteredPersonsCompleted(this, new GetRegisteredPersonsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetRegisteredPersonsAsync(int startIndex, int numberOfPersons) {
            this.GetRegisteredPersonsAsync(startIndex, numberOfPersons, null);
        }
        
        public void GetRegisteredPersonsAsync(int startIndex, int numberOfPersons, object userState) {
            if ((this.onBeginGetRegisteredPersonsDelegate == null)) {
                this.onBeginGetRegisteredPersonsDelegate = new BeginOperationDelegate(this.OnBeginGetRegisteredPersons);
            }
            if ((this.onEndGetRegisteredPersonsDelegate == null)) {
                this.onEndGetRegisteredPersonsDelegate = new EndOperationDelegate(this.OnEndGetRegisteredPersons);
            }
            if ((this.onGetRegisteredPersonsCompletedDelegate == null)) {
                this.onGetRegisteredPersonsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetRegisteredPersonsCompleted);
            }
            base.InvokeAsync(this.onBeginGetRegisteredPersonsDelegate, new object[] {
                        startIndex,
                        numberOfPersons}, this.onEndGetRegisteredPersonsDelegate, this.onGetRegisteredPersonsCompletedDelegate, userState);
        }
    }
}
